config/routes.rb
Rails.application.routes.draw do

  resources :albums do
    resources :photos
  end
  devise_for :users
  root 'albums#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :album
  has_one_attached :file
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
    authorize @album
  end

  # POST /albums
  # POST /albums.json

  def create
    new_album_params = album_params.merge ({user_id: current_user.id})
    @album = Album.new(new_album_params)

     authorize @album

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    authorize @album
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    authorize @album
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:date, :name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = 'You are unauthorized to do this action.'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :set_album
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]

  # GET /photos
  # GET /photos.json
  def index
    @photos = @album.photos
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    authorize @photo
  end

  # GET /photos/new
  def new
    @photo = Photo.new(album: @album)
  end

  # GET /photos/1/edit
  def edit
    authorize @photo
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params.merge(album: @album))

    authorize @photo

    respond_to do |format|
      if @photo.save
        format.html { redirect_to album_path(@album), notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    authorize @photo
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to album_photo_path(@album, @photo), notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    authorize @photo
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to album_photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def set_album
      @album = Album.find(params[:album_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:description, :file)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_field :date %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Albums</h1>

<table class='table'>
  <thead>
    <tr>
      <th>User</th>
      <th>Date</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.user.email %></td>
        <td><%= album.date.strftime "%m/%d/%Y" %></td>
        <td><%= album.name %></td>
        <td><%= link_to 'Show', album, class: 'btn btn-success' %></td>
        <% if policy(album).update? %>
        <td><%= link_to 'Edit', edit_album_path(album), class: 'btn btn-warning' %></td>
        <% end %>
        <% if policy(album).destroy? %>
        <td><%= link_to 'Delete', album, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if policy(Album.new).create? %>
<%= link_to 'Add Album', new_album_path, class: "btn btn-primary" %>
<% end %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<% content_for :jumbotron do %>
<div class="jumbotron">
  <div class="row">
    <div class="col-10">
      <h1><%= @album.name  %></h1>
      <p> By: <%= @album.user.email %></p>
      <td><%= @album.date.strftime "%m/%d/%Y" %></td>
    </div>
    <div class="col-2">
      <% if policy(@album).update? %>
      <%= link_to 'New Photo', new_album_photo_path(@album), class: "btn btn-primary" %>
      <%= link_to 'Edit', edit_album_path(@album), class: 'btn btn-secondary' %>
      <% end %>
    </div>
  </div>
</div>
<% end %>

<% @album.photos.each do | photo | %>
<%= content_tag 'div', class: 'modal fade', id: "photo#{photo.id}", tabindex: "-1", role: 'dialog' do %>
<div class='modal-dialog' role='document'>
  <div class="modal-content">
    <div class="modal-body">
      <%= image_tag photo.file, class: 'img-fluid mx-auto d-block' %>
      <p><%= photo.description %></p>
    </div>
  </div>
</div>
<% end %>
<%= image_tag photo.file, width: 256, height: 256, class: 'img-thumbnail', 'data-toggle' => "modal", "data-target" => "#photo#{photo.id}", style: 'cursor: pointer;' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photon</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary shadow">
    <%= link_to 'Photon', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <ul class='navbar-nav flex-row ml-md-auto d-none d-md-flex'>
      <% if user_signed_in? %>
      <li class='nav-item'>Logged in as <span class='font-weight-bold'><%= current_user.email %></span></li>
      <li class='nav-item px-2'><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'text-secondary text-right' %></li>
      <% else %>
      <li class="nav-item px-2"><%= link_to 'Sign Up', new_user_registration_path, class: 'text-secondary' %></li>
      |
      <li class='nav-item px-2'><%= link_to 'Sign In', new_user_session_path, class: 'text-secondary' %></li>
      <% end %>
    </ul>
  </nav>
  <%= yield :jumbotron %>
  <div class="container page-content">
    <% if flash.key?(:alert) %>
    <div class="alert alert-danger alert-dismissable fade show my-4" role="alert">
      <%= flash[:alert] %>
      <button type="button" class="close" data-dismiss='alert'>
        <span aria-hidden='true'>&times;</span>
      </button>
    </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true, url: [@album, photo]) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', album_photo_path(@photo) %> |
<%= link_to 'Back', album_photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Album</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.album.name %></td>
        <td><%= photo.description %></td>
        <td><%= link_to 'Show', album_photo_path(album_id: @album.id, id: photo.id), class: 'btn btn-success' %></td>
        <td><%= link_to 'Edit', edit_album_photo_path(album_id: @album.id, id: photo.id), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Destroy', album_photo_path(id: photo.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Photo', new_album_photo_path(@album) %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', album_path(@album) %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Album:</strong>
  <%=  @photo.album.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @photo.description %>
</p>

<%= image_tag @photo.file %>
<br>
<%= link_to 'Edit', edit_album_photo_path(@album, @photo) %> |
<%= link_to 'Back', album_photos_path(@album) %>